export type CNPVSeedOutcome = 'Pending' | 'Approved'

export interface CNPVEventSeed {
  externalKey: string
  companyName: string
  symbols: string
  drugName: string
  applicationType: string
  therapeuticArea: string
  eventDescription: string
  outcome: CNPVSeedOutcome
  source: string
  newsLinks?: string[]
  cnpvAwardDate?: string
  publicActionDate?: string
  outcomeDate?: string
  nctId?: string
  otherApprovals?: string
  matchCompanyNames?: string[]
  matchDrugNames?: string[]
}

const FDA_CNPV_PROGRAM_URL = 'https://www.fda.gov/industry/commissioners-national-priority-voucher-cnpv-pilot-program'
const FDA_CNPV_FIRST_BATCH_URL = 'https://www.fda.gov/news-events/press-announcements/fda-awards-first-ever-national-priority-vouchers-nine-sponsors'
const FDA_CNPV_SECOND_BATCH_URL = 'https://www.fda.gov/news-events/press-announcements/fda-awards-second-batch-national-priority-vouchers'
const FDA_CNPV_FIRST_APPROVAL_URL = 'https://www.fda.gov/news-events/press-announcements/first-approval-commissioners-national-priority-voucher-pilot-program-strengthens-domestic-antibiotic'
const FDA_CNPV_PROACTIVE_AWARD_URL = 'https://www.fda.gov/news-events/press-announcements/fda-proactively-awards-national-priority-voucher-based-strong-phase-3-study-results'
const FDA_CNPV_TWO_VOUCHERS_URL = 'https://www.fda.gov/news-events/press-announcements/fda-grants-two-national-priority-vouchers'
const FDA_CNPV_SECOND_APPROVAL_URL = 'https://www.fda.gov/news-events/press-announcements/fda-grants-second-approval-under-national-priority-voucher-pilot-program'
const FDA_CNPV_THIRD_APPROVAL_URL = 'https://www.fda.gov/news-events/press-announcements/fda-grants-third-approval-under-national-priority-voucher-program'

export const CNPV_EVENT_SEEDS: CNPVEventSeed[] = [
  {
    externalKey: 'cnpv/pergoveris',
    companyName: 'EMD Serono, Inc.',
    symbols: '',
    drugName: 'Pergoveris',
    applicationType: 'CNPV',
    therapeuticArea: 'Reproductive Health',
    eventDescription: 'Pergoveris for infertility treatment in assisted reproductive technology.',
    outcome: 'Pending',
    source: FDA_CNPV_FIRST_BATCH_URL,
    newsLinks: ['https://www.emdserono.com/us-en/pi/pergoveris-prefilled-pen.pdf'],
    cnpvAwardDate: '2025-10-16',
  },
  {
    externalKey: 'cnpv/teplizumab',
    companyName: 'Sanofi',
    symbols: 'SNY',
    drugName: 'Teplizumab',
    applicationType: 'CNPV',
    therapeuticArea: 'Endocrinology',
    eventDescription: 'Teplizumab for delaying progression to stage 3 type 1 diabetes.',
    outcome: 'Pending',
    source: FDA_CNPV_FIRST_BATCH_URL,
    newsLinks: ['https://www.sanofi.com/en/our-science/our-medicines/tzield'],
    cnpvAwardDate: '2025-10-16',
  },
  {
    externalKey: 'cnpv/cytisinicline',
    companyName: 'Achieve Life Sciences Inc.',
    symbols: 'ACHV',
    drugName: 'Cytisinicline',
    applicationType: 'NDA',
    therapeuticArea: 'Addiction Medicine',
    eventDescription: 'Cytisinicline for smoking cessation.',
    outcome: 'Pending',
    source: 'https://ir.achievelifesciences.com/news-events/press-releases/detail/238/achieve-life-sciences-announces-fda-acceptance-of-cytisinicline-new-drug-application-for-treatment-of-nicotine-dependence-for-smoking-cessation',
    newsLinks: [
      FDA_CNPV_FIRST_BATCH_URL,
      'https://ir.achievelifesciences.com/news-events/press-releases/detail/243/achieve-life-sciences-receives-fda-commissioners-national-priority-voucher-for-cytisinicline-for-treatment-of-nicotine-dependence-for-e-cigarette-or-vaping-cessation',
      'https://ir.achievelifesciences.com/news-events/press-releases/detail/175/achieve-life-sciences-reports-statistically-significant-smoking-cessation-benefit-for-cytisinicline-in-second-confirmatory-phase-3-clinical-trial',
    ],
    cnpvAwardDate: '2025-10-16',
    publicActionDate: '2026-06-20',
    nctId: 'NCT06154382',
    otherApprovals: 'Investigational product. FDA accepted the NDA on 2025-12-23 with a PDUFA goal date of 2026-06-20; no FDA approval announced as of 2026-03-06.',
  },
  {
    externalKey: 'cnpv/db-oto',
    companyName: 'Regeneron Pharmaceuticals, Inc.',
    symbols: 'REGN',
    drugName: 'DB-OTO',
    applicationType: 'CNPV',
    therapeuticArea: 'Otolaryngology',
    eventDescription: 'DB-OTO for otoferlin-related congenital hearing loss.',
    outcome: 'Pending',
    source: FDA_CNPV_FIRST_BATCH_URL,
    newsLinks: ['https://investor.regeneron.com/news-releases/news-release-details/regeneron-acquires-decibel-therapeutics'],
    cnpvAwardDate: '2025-10-16',
  },
  {
    externalKey: 'cnpv/cenegermin-bkbj',
    companyName: 'Dompe',
    symbols: '',
    drugName: 'Cenegermin-bkbj',
    applicationType: 'BLA',
    therapeuticArea: 'Ophthalmology',
    eventDescription: 'Intranasal cenegermin-bkbj for nonarteritic anterior ischemic optic neuropathy.',
    outcome: 'Pending',
    source: 'https://www.dompe.com/media/news/press-release/dompe-s-program-in-naion-selected-for-landmark-fda-commissioner-s-national-priority-voucher-program/',
    newsLinks: [
      FDA_CNPV_FIRST_BATCH_URL,
      'https://www.dompe.com/us/media/news/press-release/dompe-receives-fda-approval-cenegermin-eye-drops-first-in-class-recombinant-human-nerve-growth-factor-with-potential-to-completely-heal-rare-neurotrophic-keratitis/',
      'https://www.dompe.com/science/disease-focus/non-arteritic-anterior-ischemic-optic-neuropathy/',
    ],
    cnpvAwardDate: '2025-10-16',
    publicActionDate: '2026-06-18',
    nctId: 'NCT05551650',
    otherApprovals: 'Cenegermin-bkbj is already FDA-approved as Oxervate ophthalmic solution for neurotrophic keratitis. Dompe disclosed FDA acceptance of the intranasal NAION BLA with a PDUFA goal date of 2026-06-18; no FDA approval announced as of 2026-03-06.',
  },
  {
    externalKey: 'cnpv/rmc-6236',
    companyName: 'Revolution Medicines, Inc.',
    symbols: 'RVMD',
    drugName: 'RMC-6236',
    applicationType: 'CNPV',
    therapeuticArea: 'Oncology',
    eventDescription: 'RMC-6236 for RAS-mutant pancreatic and other solid tumors.',
    outcome: 'Pending',
    source: FDA_CNPV_FIRST_BATCH_URL,
    newsLinks: ['https://ir.revmed.com/news-releases/news-release-details/revolution-medicines-reports-positive-clinical-updates-rmc-6236'],
    cnpvAwardDate: '2025-10-16',
  },
  {
    externalKey: 'cnpv/bitopertin',
    companyName: 'Disc Medicine, Inc.',
    symbols: 'IRON',
    drugName: 'Bitopertin',
    applicationType: 'CNPV',
    therapeuticArea: 'Hematology',
    eventDescription: 'Bitopertin for erythropoietic protoporphyria.',
    outcome: 'Pending',
    source: FDA_CNPV_FIRST_BATCH_URL,
    newsLinks: ['https://ir.discmedicine.com/news-events/press-releases/detail/48/disc-medicine-announces-positive-phase-3-results-for-bitopertin-in-erythropoietic-protoporphyria'],
    cnpvAwardDate: '2025-10-16',
  },
  {
    externalKey: 'cnpv/ketamine',
    companyName: 'Phlow Corp.',
    symbols: '',
    drugName: 'Ketamine',
    applicationType: 'CNPV',
    therapeuticArea: 'Anesthesia',
    eventDescription: 'Ketamine injectable product prioritized for domestic manufacturing resilience and hospital supply.',
    outcome: 'Pending',
    source: FDA_CNPV_FIRST_BATCH_URL,
    newsLinks: ['https://phlow-usa.com/2025/11/13/phlow-awarded-national-priority-voucher-for-domestic-ketamine-production/'],
    cnpvAwardDate: '2025-10-16',
  },
  {
    externalKey: 'cnpv/augmentin-xr',
    companyName: 'USAntibiotics, Inc.',
    symbols: '',
    drugName: 'Augmentin XR',
    applicationType: 'CNPV',
    therapeuticArea: 'Infectious Disease',
    eventDescription: 'Augmentin XR for bacterial infections requiring extended-release amoxicillin and clavulanate.',
    outcome: 'Approved',
    source: FDA_CNPV_FIRST_APPROVAL_URL,
    newsLinks: [FDA_CNPV_FIRST_BATCH_URL],
    cnpvAwardDate: '2025-10-16',
    publicActionDate: '2025-12-09',
    outcomeDate: '2025-12-09',
  },
  {
    externalKey: 'cnpv/zongertinib',
    companyName: 'Boehringer Ingelheim Pharmaceuticals, Inc.',
    symbols: '',
    drugName: 'Zongertinib',
    applicationType: 'CNPV',
    therapeuticArea: 'Oncology',
    eventDescription: 'Zongertinib (Hernexeos) for previously treated HER2-mutant non-small cell lung cancer.',
    outcome: 'Approved',
    source: FDA_CNPV_SECOND_APPROVAL_URL,
    newsLinks: [FDA_CNPV_SECOND_BATCH_URL],
    cnpvAwardDate: '2025-11-06',
    publicActionDate: '2026-02-26',
    outcomeDate: '2026-02-26',
  },
  {
    externalKey: 'cnpv/bedaquiline',
    companyName: 'Johnson & Johnson',
    symbols: 'JNJ',
    drugName: 'Bedaquiline',
    applicationType: 'CNPV',
    therapeuticArea: 'Infectious Disease',
    eventDescription: 'Bedaquiline pediatric formulation for pulmonary multidrug-resistant tuberculosis in young children.',
    outcome: 'Pending',
    source: FDA_CNPV_SECOND_BATCH_URL,
    newsLinks: ['https://www.jnj.com/media-center/press-releases/johnson-johnson-announces-fda-acceptance-of-new-drug-application-for-bedaquiline-for-children-under-five-with-pulmonary-multidrug-resistant-tuberculosis'],
    cnpvAwardDate: '2025-11-06',
  },
  {
    externalKey: 'cnpv/dostarlimab',
    companyName: 'GSK plc',
    symbols: 'GSK',
    drugName: 'Dostarlimab',
    applicationType: 'CNPV',
    therapeuticArea: 'Oncology',
    eventDescription: 'Dostarlimab for mismatch repair-deficient locally advanced rectal cancer.',
    outcome: 'Pending',
    source: FDA_CNPV_SECOND_BATCH_URL,
    newsLinks: ['https://www.gsk.com/en-gb/media/press-releases/gsk-announces-jemperli-dostarlimab-has-received-fda-priority-review/'],
    cnpvAwardDate: '2025-11-06',
  },
  {
    externalKey: 'cnpv/casgevy',
    companyName: 'Vertex Pharmaceuticals Incorporated',
    symbols: 'VRTX',
    drugName: 'Casgevy',
    applicationType: 'CNPV',
    therapeuticArea: 'Genetic Disease',
    eventDescription: 'Casgevy for sickle cell disease.',
    outcome: 'Pending',
    source: FDA_CNPV_SECOND_BATCH_URL,
    newsLinks: ['https://investors.vrtx.com/news-releases/news-release-details/vertex-announces-fda-acceptance-supplemental-biologics-license'],
    cnpvAwardDate: '2025-11-06',
  },
  {
    externalKey: 'cnpv/orforglipron',
    companyName: 'Eli Lilly and Company',
    symbols: 'LLY',
    drugName: 'Orforglipron',
    applicationType: 'CNPV',
    therapeuticArea: 'Cardiometabolic',
    eventDescription: 'Orforglipron for obesity.',
    outcome: 'Pending',
    source: FDA_CNPV_SECOND_BATCH_URL,
    newsLinks: ['https://investor.lilly.com/news-releases/news-release-details/lillys-oral-glp-1-orforglipron-shows-positive-phase-3-results'],
    cnpvAwardDate: '2025-11-06',
  },
  {
    externalKey: 'cnpv/wegovy',
    companyName: 'Novo Nordisk',
    symbols: 'NVO',
    drugName: 'Wegovy',
    applicationType: 'CNPV',
    therapeuticArea: 'Cardiometabolic',
    eventDescription: 'Wegovy for obesity.',
    outcome: 'Pending',
    source: FDA_CNPV_SECOND_BATCH_URL,
    newsLinks: ['https://www.novonordisk-us.com/products/product-pricing/wegovy.html'],
    cnpvAwardDate: '2025-11-06',
  },
  {
    externalKey: 'cnpv/tec-dara',
    companyName: 'Johnson & Johnson',
    symbols: 'JNJ',
    drugName: 'Tec-Dara',
    applicationType: 'CNPV',
    therapeuticArea: 'Oncology',
    eventDescription: 'Tec-Dara (teclistamab and daratumumab) for relapsed or refractory multiple myeloma.',
    outcome: 'Approved',
    source: FDA_CNPV_THIRD_APPROVAL_URL,
    newsLinks: [FDA_CNPV_PROACTIVE_AWARD_URL],
    cnpvAwardDate: '2025-12-15',
    publicActionDate: '2026-03-05',
    outcomeDate: '2026-03-05',
  },
  {
    externalKey: 'cnpv/enlicitide-decanoate',
    companyName: 'Merck & Co., Inc.',
    symbols: 'MRK',
    drugName: 'Enlicitide decanoate',
    applicationType: 'CNPV',
    therapeuticArea: 'Cardiometabolic',
    eventDescription: 'Enlicitide decanoate for hypercholesterolemia.',
    outcome: 'Pending',
    source: FDA_CNPV_TWO_VOUCHERS_URL,
    newsLinks: ['https://www.merck.com/news/merck-announces-positive-phase-3-results-for-enlicitide-decanoate/'],
    cnpvAwardDate: '2025-12-19',
  },
  {
    externalKey: 'cnpv/sacituzumab-tirumotecan',
    companyName: 'Merck & Co., Inc.',
    symbols: 'MRK',
    drugName: 'Sacituzumab Tirumotecan',
    applicationType: 'CNPV',
    therapeuticArea: 'Oncology',
    eventDescription: 'Sacituzumab tirumotecan for advanced or metastatic EGFR-mutant nonsquamous non-small cell lung cancer.',
    outcome: 'Pending',
    source: FDA_CNPV_TWO_VOUCHERS_URL,
    newsLinks: ['https://www.merck.com/news/merck-and-kelun-biotech-announce-positive-phase-3-results-for-sacituzumab-tirumotecan/'],
    cnpvAwardDate: '2025-12-19',
  },
]
