import { baseSepolia } from 'viem/chains'

export const SEASON4_CHAIN = baseSepolia
export const SEASON4_CHAIN_ID = baseSepolia.id
export const SEASON4_CHAIN_NAME = baseSepolia.name

export const MOCK_USDC_DECIMAL_PLACES = 6
export const MOCK_USDC_DISPLAY_SCALE = 1_000_000

export const PRICE_E18 = BigInt('1000000000000000000')
export const PRICE_INPUT_SCALE = BigInt(MOCK_USDC_DISPLAY_SCALE)
export const DEFAULT_INITIAL_PRICE_YES_E18 = PRICE_E18 / BigInt(2)

export const SEASON4_INDEXER_MAX_LOG_RANGE = BigInt(9_999)
export const DEFAULT_SEASON4_INDEXER_CONFIRMATIONS = 3
export const DEFAULT_SEASON4_INDEXER_INTERVAL_SECONDS = 30
export const DEFAULT_SEASON4_MODEL_MAX_MARKETS_PER_CYCLE = 1

export const SEASON4_RPC_BLOCK_POLL_ATTEMPTS = 10
export const SEASON4_RPC_BLOCK_POLL_DELAY_MS = 1_000
export const SEASON4_APPROVE_TX_GAS_LIMIT = BigInt(90_000)
export const SEASON4_TRADE_TX_GAS_LIMIT = BigInt(500_000)

export const DEFAULT_SEASON4_MODEL_ETH_TOP_UP_WEI = BigInt(20_000_000_000_000)
export const MIN_SEASON4_MODEL_ETH_BALANCE_WEI = BigInt(10_000_000_000_000)

export const DEFAULT_SEASON4_TRADE_SLIPPAGE_BPS = 100
export const MAX_SEASON4_TRADE_SLIPPAGE_BPS = 5_000

export const SEASON4_ONCHAIN_INDEXER_ADVISORY_LOCK_KEY = 44_040_001
export const SEASON4_MODEL_CYCLE_ADVISORY_LOCK_KEY = 44_040_002
